#pragma once

#define LED_NUM 3
#define LED_PINS { C8, C7, C6 }

#define BOARD_OTG_NOVBUSSENS 1

#define USB_ENDPOINTS_ARE_REORDERABLE

#ifndef EARLY_INIT_PERFORM_BOOTLOADER_JUMP
#    define EARLY_INIT_PERFORM_BOOTLOADER_JUMP TRUE
#endif

#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE