#pragma once

enum BtCommEvent {
    UNKNOWN = 0,

    // Events from BT module
    MODULE_BOOTED,
    PAIRING_STARTED,
    CONNECTED,
    CONNECTION_STARTED,
    DISCONNECTED,
    MODULE_WAKED_UP,
    MODULE_SLEPT,
    MODULE_DEEP_SLEPT,

    // Inner events
    ENTER_DEEP_SLEEP_BY_USER,
    UNEXPECTED_COMMAND_RECEIVED,
    PREPARATION_COMPLETED,
    DISCONNECTION_STARTED
};
