#pragma once

#define AT_PREFIX "AT"

#define ENABLE "ENABLE"
#define DISABLE "DISABLE"

// ==============================================
// Commands
// ==============================================

#define COMMAND_OK "OK"
#define COMMAND_AT "AT"

#define COMMAND_UART_SETTINGS "+UART"
#define COMMAND_VERSION_SETTINGS "+VERSION"
#define COMMAND_NAME_SETTINGS "+NAME"
#define COMMAND_AUTOIDLE_SETTINGS "+AUTOIDLE"
#define COMMAND_IDLETIMES_SETTINGS "+IDLETIMES"
#define COMMAND_VIDPID_SETTINGS "+VIDPID"
#define COMMAND_EVENT "+EVENT"
#define COMMAND_AUTOEVENT_SETTINGS "+AUTOEVENT"
#define COMMAND_HID "+HID"
#define COMMAND_SELECTED_DEVICE "+KEYBOARD"
#define COMMAND_DISCOVER "+DISCOVER"
#define COMMAND_CONNECT "+CONN"
#define COMMAND_DISCONNECT "+DISCONN"
#define COMMAND_DEEPSLEEP "+DEEPSLEEP"
