#pragma once

enum BtCommEvent {
    UNKNOWN = 0,

    // Events from BT module
    MODULE_BOOTED,
    PAIRING_STARTED,
    CONNECTED,
    CONNECTION_STARTED,
    DISCONNECTED,
    MODULE_WAKED_UP,
    MODULE_SLEPT,

    // Inner events
    UNEXPECTED_COMMAND_RECEIVED,
    INITIALIZE_COMPLETED,
    DISCONNECTION_STARTED
};
